runtime: php83

runtime_config:
  document_root: caretech_solutions

handlers:
  # Serve a directory as a static resource.
  - url: /css
    static_dir: css

  #Added the js directory.
  - url: /js
    static_dir: js

  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$

  # Serve your app through a front controller at index.php or public/index.php.
  - url: /.*
    script: auto

entrypoint:
  serve handler.php

# Updated the Enviroment Variables for PDO.
env_variables:
  GOOGLE_STORAGE_BUCKET: caretechsolutions.appspot.com 
  CLOUDSQL_DSN: mysql:unix_socket=/cloudsql/caretechsolutions:us-central1:caretech-solutions-db
  CLOUDSQL_USER: root  
  CLOUDSQL_PASSWORD: '@KNjOzNqd)NdGART'  
  CLOUDSQL_DATABASE_NAME: caretech_solutions  
 
